-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME 
FROM(
    SELECT I.ANIMAL_ID, I.NAME, I.ANIMAL_TYPE, I.SEX_UPON_INTAKE AS ISEX, O.SEX_UPON_OUTCOME AS OSEX
    FROM ANIMAL_INS I, ANIMAL_OUTS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
) A
WHERE A.ISEX != A.OSEX