-- 코드를 입력하세요
SELECT A.NAME, A.IDATE AS DATETIME
FROM(
    SELECT I.ANIMAL_ID, I.NAME, I.DATETIME AS IDATE, NVL(O.ANIMAL_ID, 'NOOUT')AS OID 
    FROM ANIMAL_INS I
    LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY IDATE ASC
) A
WHERE A.OID = 'NOOUT' AND ROWNUM <= 3;
