-- -- 코드를 입력하세요
-- SELECT A.USER_ID, A.NICKNAME, A.TOTAL_SALES
-- FROM(
--     SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
--     FROM USED_GOODS_BOARD B
--     LEFT JOIN USED_GOODS_USER U
--     ON B.WRITER_ID = U.USER_ID
--     WHERE B.STATUS = 'DONE'
--     GROUP BY U.USER_ID, U.NICKNAME
--     HAVING SUM(B.PRICE)>=700000
-- ) A
-- ORDER BY TOTAL_SALES DESC
SELECT  B.USER_ID
    ,   B.NICKNAME
    ,   SUM(PRICE) TOTAL_SALES
FROM    USED_GOODS_BOARD    A
    ,   USED_GOODS_USER     B
WHERE   1=1
        AND A.WRITER_ID = B.USER_ID
        AND A.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING  SUM(PRICE) >= 700000 
ORDER BY TOTAL_SALES